#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check ESLint Standards
yarn lint ||
(
        echo '😤🏀👋😤 Failed linting! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
yarn check-types ||
(
    echo '😳😥❌😳 Failed Type check! 😳😥❌😳
                Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Looks good to me, I am pushing this now... ✅✅✅✅'